### PR TITLE
Add Number support to text fields (in preparation for fallback rate support)

### PR DESCRIPTION
**Pull request by jkudish**
This PR seeks to add `Number` support to the `textField` component, in preparation for supporting the fallback rate setting.

This PR should be tested in conjunction with https://github.com/Automattic/woocommerce-connect-server/pull/300 -- where full testing instructions are included.

See https://github.com/Automattic/woocommerce-connect-client/issues/265

cc @nabsul @allendav @jeffstieler @DanReyLop

### CODE REVIEW

**Comment by allendav** [comment]
@jkudish @DanReyLop - I'm inclined to not mix number and non-number handling in one component - I think it might make maintenance more straightforward.  What do you think about shelving this PR in favor of the approach in https://github.com/Automattic/woocommerce-connect-client/pull/388

**Comment by DanReyLop** [comment]
#388 is an ad-hoc solution for the rate adjustment fields (which don't have schema), this is a bit more general solution for having fields with `number` schema type. This solution has the same problems that #388 seeks to solve (you can't type `2.05` in the Fallback rate field).

I think the quickest solution for shipping this with Alpha 2 is discarding this PR and re-implementing it using the `<NumberInput>` component (it'll be easier too when we decide to refactor if all the numeric inputs use the same component).

Let me know if you agree and I'll start working on it.

**Comment by nabsul** [comment]
Is this still being worked on?

**Comment by DanReyLop** [comment]
I've implemented a solution using the general idea of this PR and the `NumberField` component, here it is: https://github.com/Automattic/woocommerce-connect-client/pull/410

I'm closing this one.

**Pull request closed without merging**
