### PR TITLE
Change WooThemes to WooCommerce

### LINKED ISSUE #661: Update github references from https://github.com/woothemes to woocommerce
In CONTRIBUTING.md and tests/bin/install-wc-tests.sh

### PR DESCRIPTION
**Pull request by mikeyarce**
Change instances of WooThemes to be WooCommerce. 

Fixes #661

### CODE REVIEW

**Comment by allendav** [comment]
We love to have issues for each PR :) So I've opened https://github.com/Automattic/woocommerce-connect-client/issues/661

**Comment by allendav** [comment]
@mikeyarce - needs rebasing - probably because I already fixed woocommerce-connect-client.php in a previous commit

**Comment by mikeyarce** [comment]
@allendav lol well at least we both thought of it! :)

I rebased and pushed again.

**Comment by allendav** [comment]
:shipit: and then we'll fix #663

**Pull request merged**
