### PR TITLE
Fix doc URL

### PR DESCRIPTION
**Pull request by SiR-DanieL**
Fixed URL to use docs.woocommerce.com instead of the old docs.woothemes.com

### CODE REVIEW

**Comment by nabsul** [comment]
:shipit:

**Comment by SiR-DanieL** [comment]
@nabsul should I merge or someone else will?

**Comment by nabsul** [comment]
@SiR-DanieL The person that wrote the code usually has that honor :smile:

**Comment by SiR-DanieL** [comment]
I wouldn't call that "code" but thanks for the honor :D

**Pull request merged**
