### PR TITLE
Upgrade several outdated npm modules

### PR DESCRIPTION
**Pull request by jkudish**
It's important to keep dependencies up to date, to prevent future issues and to keep maximum compatibility with latest versions of node and of Calypso. This PR seeks to upgrade several outdated npm modules. Specifically the following npm modules are updated:

* babel-plugin-add-module-exports
* eslint
* eslint-plugin-react
* jsdom
* mocha
* mocha-webpack
* node-sass
* webpack-notifier
* babel-core
* babel-preset-es2015
* classnames
* dompurify
* lodash

The outdated modules were determined by `npm outdated`. This PR doesn't include upgrades for `react`, `react-dom` nor `react-addon-utils` which are also outdated. There were problems encoutered when upgrading React, so I opened #371 instead.

Since this update touches quite a few things, it should be tested carefully. Here are the steps to test:

* Checkout this branch
* Delete `node_modules` and clean npm's cache -- `rm -rf node_modules && npm cache clean`
* Run `npm install`
* Run `npm test` -- ensure tests pass
* Run `npm dist` -- ensure the build succeeeds 
* Remove/comment out `WOOCOMMERCE_CONNECT_DEV_SERVER_URL` from your `wp-config.php` file if it was set
* Load a WCC shipping zone settings page, and make sure it loads
* Ensure there are no console errors or warnings
* Interact with the WCC shipping zone settings page -- make sure fields are editable, the package modal operates as expected, and that you're able to save settings. Ensure there are no console errors or warnings as you interact with the page.
* Load the WCC system status page, and ensure the same as above
* Run `npm start` -- ensure the build succeeeds
* Re-add the `WOOCOMMERCE_CONNECT_DEV_SERVER_URL` with the appropriate localhost url
* Repeat the steps above to ensure everything loads/operates as expected
* Make a small (ideally visual) change to a component and make sure that hot reloading still works as expected

Related: #367

### CODE REVIEW

**Comment by nabsul** [comment]
Is this supposed to be failing?

**Comment by jkudish** [comment]
No it's not.

**Comment by jkudish** [comment]
The failure seemed unrelated, so I've restarted the one php version that failed. I think it was just a glitch.

**Comment by jkudish** [comment]
I was correct. The build is passing now.

**Comment by nabsul** [comment]
Tested locally. I tried it on my sandbox but I'm getting some warnings, however, I get the same errors on the master branch as well, so I think they're not related.

:shipit:

**Pull request merged**
