### PR TITLE
Add TOS banner

### PR DESCRIPTION
**Pull request by robobot3000**
Adds #24 

screen shot 2016-10-25 at 22 06 21
- Implemented parts the design from #626
- Wired up "Agree" and "No thanks" buttons to enable Connect or deactivate it
- Added killswitches to the rendering methods/hooks to prevent the Connect UI from being rendered if the TOS haven't been accepted
- Added a killswitch preventing any request from being sent to the server unless TOS have been accepted

Still todo:
- [ ] Update the colors, links and banner text

CC @kellychoffman @allendav @jameskoster

### CODE REVIEW

**Comment by kellychoffman** [comment]
Is this still in progress or would you like us to update the colors? 

Just one other thing: lets nix the sentence with the link to the shipping settings re: https://github.com/Automattic/woocommerce-connect-client/issues/626#issuecomment-256058093.

**Comment by robobot3000** [comment]
This is just awaiting the url to the TOS page. I updated the colors after talking to @jameskoster but feel free to check it out and change it if needed.

screen shot 2016-10-26 at 14 22 47

**Comment by allendav** [comment]
We'll need to tweak the copy a bit - legal wants two links - one for a privacy document and one for the terms of service.  The URLs will probably be https://woocommerce.com/terms-conditions/connect-privacy and https://woocommerce.com/terms-conditions/connect-terms

Let's change the text to 

Before we can begin empowering your store with simpler shipping we need your agreement to our privacy policy and terms of service.

With "privacy policy" and "terms of service" as links

That's correct, right @kellychoffman @pesieminski @jennyzhu ?

**Comment by jennyzhu** [comment]
@allendav The language we should use is [here](https://github.com/Automattic/woocommerce-connect-client/issues/626#issuecomment-256500391), but including the details here too:

> By clicking "Connect" below, you agree to our [Terms of Service](https://woocommerce.com/terms-conditions/) and understand that Connect for WooCommerce passes some data to external servers in order to enable its features. You can find more information about how your store's data is handled [here](https://woocommerce.com/terms-conditions/connect-privacy).

There's no magic to the word "CONNECT" on the button. Just my suggestion, which I thought was a nice reinforcement of the name of the plugin. The only requirement is that the text on the button must match the text we use in the sentence above it. If we say "by clicking "Connect" the button should say "Connect."

**Comment by kellychoffman** [comment]
@avivapinchas updated the copy to read:

**Connect for WooCommerce is almost ready to go!** 
> We just need to make sure you agree to our [terms of service](url). 

This was before the privacy requirement and Paul's https://github.com/Automattic/woocommerce-connect-client/issues/626#issuecomment-256500391 about adding the term 'connect'. This would also align with [Jetpack's admin notice](https://cloudup.com/cjwtBws9Pgh) and the 'connect' button in the proposed design for the setup wizard.

**Comment by jennyzhu** [comment]
@kellychoffman Thanks for letting us know! To clarify though, let's please use [this language](https://github.com/Automattic/woocommerce-connect-client/pull/640#issuecomment-257657224).

**Comment by kellychoffman** [comment]
Thanks @jennyzhu. For some reason, I only saw the link to the comment, not the actual quoted text. Ignore me :)

**Comment by allendav** [comment]
the "Terms of Service" link needs to go to https://woocommerce.com/terms-conditions/connect-terms and the "here" link to https://woocommerce.com/terms-conditions/connect-privacy

**Comment by robobot3000** [comment]
That's where they link to for me: https://woocommerce.com/terms-conditions/connect-terms and https://woocommerce.com/terms-conditions/connect-privacy

Both pages 404 at the moment. Are you seeing something else?

**Comment by allendav** [comment]
@robobot3000 - just need to fix those links and then this is good to go i think

what do you think @kellychoffman ?

**Comment by kellychoffman** [comment]
Fixing the colors as we speak. Stand by.

**Comment by allendav** [comment]
my clone of your branch was out of date - this looks good to me link wise after all

**Comment by kellychoffman** [comment]
All set from my end. :shipit:

**Comment by robobot3000** [comment]
Thanks everyone :) Merged #640

**Comment by jennyzhu** [comment]
@allendav @robobot3000 

> the "Terms of Service" link needs to go to https://woocommerce.com/terms-conditions/connect-terms and the "here" link to https://woocommerce.com/terms-conditions/connect-privacy

Minor correction: the "Terms of Service" link should point to the main [Woo TOS](https://woocommerce.com/terms-conditions/). See my above comment or PES' [here](https://github.com/Automattic/woocommerce-connect-client/issues/626#issuecomment-256500391). Thanks!

**Pull request merged**
