### PR TITLE
Add special display for when there are zero packages

### PR DESCRIPTION
**Pull request by nabsul**
#274

@kellychoffman

### CODE REVIEW

**Comment by kellychoffman** [comment]
@nabsul: I've added the icon, messaging and the styles to go along with it. 

screen shot 2016-05-24 at 4 32 43 pm

**Comment by jkudish** [comment]
What happens when a user doesn't have packages defined? I think that's what the copy should explain, and then offer to add custom/predefined ones.

**Comment by nabsul** [comment]
Oh, if we have no packages, then we should force the user to select the "ship individually" radio button as well.

**Comment by kellychoffman** [comment]
Mentioning the predefined packages is a good idea. 

> Oh, if we have no packages, then we should force the user to select the "ship individually" radio button as well.

What do you mean? My thought that this is the messaging they'd see when they first hit the settings page and thus haven't added any info, packages included.

**Comment by nabsul** [comment]
@kellychoffman Regarding the "ship individually" comment, I'll create a separate issue around this topic. There's a couple of routes we can take and should discuss before deciding.

**Comment by nabsul** [comment]
Rebased the code.

**Comment by jeffstieler** [comment]
This looks good and tests well. I'd recommend splitting the package list rendering logic into a few functions.

:shipit: or refactor. Please set back to "needs review" if you change code.

**Pull request merged**
