### PR TITLE
Make the global notices be visible on top of the modals.

### LINKED ISSUE #649: Design: Errors continue to be displayed "below" the labels modal
Errors that occur while using the label modal should appear in the modal itself, not beneath it.

Needs design.

screen shot 2016-10-27 at 11 33 04 am

### PR DESCRIPTION
**Pull request by DanReyLop**
Fixes #649, #650 

To test, go purchase a label, and force an error. One way to do that is filling the entire form and, just before hitting the "Purchase" button, kill the server process. Check that you can interact with the notice (select its text, dismiss it) without closing the dialog.

This wasn't as easy as changing the `.global-notices` z-index. Turns out, any click outside of a `Dialog` closes it, and that includes clicking the notice. I created a simple wrapper component around Calypso's `Dialog`, that has the logic to only interpret a click as "close" if it's a click in the dialog's `backdrop`.

@allendav @jeffstieler @nabsul @robobot3000

### CODE REVIEW

**Comment by kellychoffman** [comment]
👍 Works for me.

**Comment by allendav** [comment]
This blows up for me when testing against the latest master.  Any thoughts?

screen shot 2016-11-15 at 4 20 37 pm

**Comment by robobot3000** [comment]
Rebase would help, but this PR is unrelated to the error.

**Comment by DanReyLop** [comment]
@allendav I've rebased, but as Marcin said, it doesn't look the error has anything to do with this PR.

**Comment by allendav** [comment]
Agreed. :shipit:

**Pull request merged**
